<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#">

<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css" rel="stylesheet" type="text/css">
    <link href="//cdn.jsdelivr.net/qtip2/2.0.1/jquery.qtip.min.css" rel="stylesheet" type="text/css">
    <link href="/css/prisma-main.min.css" rel="stylesheet" type="text/css">
    <meta charset="utf-8">
    <meta property="og:title" content="PrISMA">
    <meta property="og:type" content="website">
    <meta property="og:url" content="http://prisma.inf.puc-rio.br">
    <meta property="og:image" content="">
    <meta property="og:site_name" content="PrISMA">
    <meta property="fb:admins" content="100001586200753">
    <title>PrISMA: Programa de Instrução à Matrícula Acadêmica</title>
    <style type="text/css">
    </style>
</head>

<body data-twttr-rendered="true">
    <div id="dialog-div" class="modal hide fade"></div>
    <div id="wrap-div">
        <div class="container-fluid">
            <div class="navbar navbar-inverse">
                <div class="navbar-inner"><span class="brand">PrISMA</span>
                    <ul class="nav pull-right">
                        <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle"><span>JULIO RIBEIRO DA SILVA</span><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/logout">Logout</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div id="content-div" class="row-fluid">
                <div id="container-div">
					<div class="page-header">
						<h1>Estatísticas de Uso</h1>
					</div>
					<h2>blablabla</h2>
					<p>alguma explicacao</p>
					<hr>
				</div>
            </div>
        </div>
        <div id="push-div"></div>
    </div>
    <div id="footer-div" class="container-fluid">
        <div class="row-fluid">
            <p>Esse projeto é uma colaboração dos alunos Julio Ribeiro, Luiza Silva, Gabriel Martinelli, André Marçal, Denis Neves, Glauber Borges e Maurício Fragale com o professor Sérgio Lifschitz. Contato: prisma@inf.puc-rio.br</p>
        </div>
    </div>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"></script>
	<script>
		$('.dropdown-toggle').dropdown();
	</script>
</body>

</html>
