<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#">

<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css" rel="stylesheet" type="text/css">
    <link href="//cdn.jsdelivr.net/qtip2/2.0.1/jquery.qtip.min.css" rel="stylesheet" type="text/css">
    <link href="/css/prisma-main.min.css" rel="stylesheet" type="text/css">
    <meta charset="utf-8">
    <meta property="og:title" content="PrISMA">
    <meta property="og:type" content="website">
    <meta property="og:url" content="http://prisma.inf.puc-rio.br">
    <meta property="og:image" content="">
    <meta property="og:site_name" content="PrISMA">
    <meta property="fb:admins" content="100001586200753">
    <title>PrISMA: Programa de Instrução à Matrícula Acadêmica</title>
    <style type="text/css">
		div#container-div{
			width: 70%;
			margin: 0 auto;
		}
    </style>
</head>

<body data-twttr-rendered="true">
    <div id="dialog-div" class="modal hide fade"></div>
    <div id="wrap-div">
        <div class="container-fluid">
            <div class="navbar navbar-inverse">
                <div class="navbar-inner"><span class="brand">PrISMA</span>
                    <ul class="nav pull-right">
                        <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle"><span><?php echo $data['username'] ?></span><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/logout">Logout</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div id="content-div" class="row-fluid">
                <div id="container-div">
					<h1 class="centered">Estatísticas de Uso</h1><br/><hr/>
					<h3>#1 Total de usuarios:
						<p><?php echo $data['qtdTotal'] ?></p>
					</h3>
					<br/><hr/>
					<h3>#2 Acesso diário: </h3>
					<p><?php echo $data['acessoDiario'] ?></p>
					<br/><hr/>
					<h3>#3 Uso por curso: </h3>
					<p><?php echo $data['usoPorCurso'] ?></p>
					<br/><hr/>
					<h3>#4 Demanda por turma: </h3>
					<p><?php echo $data['turmaDemanda'] ?></p>
					<br/><hr/>
					<h3>#4 Demanda por horario: </h3>
					<p><?php echo $data['horarioDemanda'] ?></p>
					<br/><hr/>
					<h3>#4 Media de tentativas por disciplina: </h3>
					<p><?php echo $data['disciplinaTentativaMedia'] ?></p>
					<br/><hr/>
				</div>
            </div>
        </div>
        <div id="push-div"></div>
    </div>
    <div id="footer-div" class="container-fluid">
        <div class="row-fluid">
            <p>Esse projeto é uma colaboração dos alunos Julio Ribeiro, Luiza Silva, Gabriel Martinelli, André Marçal, Denis Neves, Glauber Borges e Maurício Fragale com o professor Sérgio Lifschitz. Contato: prisma@inf.puc-rio.br</p>
        </div>
    </div>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"></script>
	<script src="http://code.highcharts.com/highcharts.js"></script>
	<script>
		$('.dropdown-toggle').dropdown();
	</script>
</body>

</html>
