<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#">

<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css" rel="stylesheet" type="text/css">
    <link href="//cdn.jsdelivr.net/qtip2/2.0.1/jquery.qtip.min.css" rel="stylesheet" type="text/css">
    <link href="//cdn.datatables.net/1.10.4/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
    <link href="/css/prisma-main.min.css" rel="stylesheet" type="text/css">
    <meta charset="utf-8">
    <meta property="og:title" content="PrISMA">
    <meta property="og:type" content="website">
    <meta property="og:url" content="http://prisma.inf.puc-rio.br">
    <meta property="og:image" content="">
    <meta property="og:site_name" content="PrISMA">
    <meta property="fb:admins" content="100001586200753">
    <title>PrISMA: Programa de Instrução à Matrícula Acadêmica</title>
    <style type="text/css">
		div#container-div{
			width: 70%;
			margin: 0 auto;
		}
    </style>
</head>

<body data-twttr-rendered="true">
    <div id="dialog-div" class="modal hide fade"></div>
    <div id="wrap-div">
        <div class="container-fluid">
            <div class="navbar navbar-inverse">
                <div class="navbar-inner"><span class="brand">PrISMA</span>
                    <ul class="nav pull-right">
                        <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle"><span><?php echo $data['username'] ?></span><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/logout">Logout</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div id="content-div" class="row-fluid">
                <div id="container-div">
					<h1 class="centered">Estatísticas de Uso</h1>
					<br/><hr/>

					<h3>#1 Total de usuarios:
						<p><?php echo $data['qtdTotal'] ?></p>
					</h3>
					<br/><hr/>

					<h3>#2 Acesso diário:</h3>
					<div id="acessoDiario"></div>
					<br/><hr/>

					<h3>#3 Uso por curso:</h3>
					<div id="usoPorCurso"></div>
					<br/><hr/>
					
					<h3>#4 Demanda por turma:</h3>
					<table id="turmaDemanda" class="display" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>Disciplina</th>
								<th>Turma</th>
								<th>Vagas</th>
								<th>Demanda</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach($data['turmaDemanda'] as $turma) { ?>
						   <tr>
								<td><?php echo $turma['FK_Disciplina'] ?></td>
								<td><?php echo $turma['Codigo'] ?></td>
								<td><?php echo $turma['Vagas'] ?></td>
								<td><?php echo $turma['Demanda'] ?></td>
							</tr>
						<?php } ?>
						</tbody>
					</table>
					<br/><hr/>

					<h3>#4 Demanda por horario:</h3>
					<table id="demandaHorario" class="display" cellspacing="0" width="100%">
						<thead>
							<tr>
								<td></td>
								<td>Segunda</td>
								<td>Terça</td>
								<td>Quarta</td>
								<td>Quinta</td>
								<td>Sexta</td>
								<td>Sábado</td>
							</tr>
						</thead>
						<tbody>
						<?php for($i = 7; $i <= 22; $i++) { ?>
							<tr>
								<td><?php echo $i.'h';?></td>
							<?php for($j = 2; $j <= 7; $j++) { ?>
								<td><?php echo $data["horarioDemanda"][$j][$i];?></td>
							<?php } ?>
							</tr>
						<?php } ?>
						</tbody>
					</table>
					<br/><hr/>

					<h3>#4 Media de tentativas por disciplina (datatables): </h3>
					<table id="disciplinaTentativas" class="display" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>Disciplina</th>
								<th>Media de tentativas</th>
							</tr>
						</thead>
						<tbody>
						<?php foreach($data['disciplinaTentativaMedia'] as $disc) { ?>
						   <tr>
								<td><?php echo $disc['FK_Disciplina'] ?></td>
								<td><?php echo $disc['MediaTentativas'] ?></td>
							</tr>
						<?php } ?>
						</tbody>
					</table>

					<br/><hr/>
				</div>
            </div>
        </div>
        <div id="push-div"></div>
    </div>
    <div id="footer-div" class="container-fluid">
        <div class="row-fluid">
            <p>Esse projeto é uma colaboração dos alunos Julio Ribeiro, Luiza Silva, Gabriel Martinelli, André Marçal, Denis Neves, Glauber Borges e Maurício Fragale com o professor Sérgio Lifschitz. Contato: prisma@inf.puc-rio.br</p>
        </div>
    </div>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"></script>
	<script src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js"></script>
	<script src="//code.highcharts.com/highcharts.js"></script>
	<script src="//code.highcharts.com/modules/exporting.js"></script>
	<script>

		$('.dropdown-toggle').dropdown();

		/* ------------------------------------------------------------------- */

		$('#turmaDemanda').DataTable();
		$('#disciplinaTentativas').DataTable();
		$('#demandaHorario').DataTable({
			"paging":   false,
			"ordering": false,
			"info":     false
		});

		/* ------------------------------------------------------------------- */

		var acessoDiarioData = <?php echo $data['acessoDiario'] ?>;
		var acessoDiarioDate = acessoDiarioData[0].Data.split('-');

		acessoDiarioDataTratada = [];
		acessoDiarioData.forEach(
			function(a)
			{
				acessoDiarioDataTratada.push(a.QuantidadeUsuario);
			}
		);

		$('#acessoDiario').highcharts({
			chart: {
				zoomType: 'x'
			},
			title: {
				text: 'Acesso Diário'
			},
			subtitle: {
				text: document.ontouchstart === undefined ?
						'Click and drag in the plot area to zoom in' :
						'Pinch the chart to zoom in'
			},
			xAxis: {
				type: 'datetime',
				minRange: 14 * 24 * 3600000 // fourteen days
			},
			yAxis: {
				title: {
					text: 'Quantidade de acessos'
				}
			},
			legend: {
				enabled: false
			},
			plotOptions: {
				area: {
					fillColor: {
						linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
						stops: [
							[0, Highcharts.getOptions().colors[0]],
							[1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
						]
					},
					marker: {
						radius: 2
					},
					lineWidth: 1,
					states: {
						hover: {
							lineWidth: 1
						}
					},
					threshold: null
				}
			},

			series: [{
				type: 'area',
				name: 'Acessos',
				pointInterval: 24 * 3600 * 1000,
				pointStart: Date.UTC(Number(acessoDiarioDate[0])-1,Number(acessoDiarioDate[1]),Number(acessoDiarioDate[2])),
				data: acessoDiarioDataTratada
			 }]
		});

		/* ------------------------------------------------------------------- */

		var usoPorCursoData = <?php echo $data['usoPorCurso'] ?>;

		var nomeCurso = [];
		var acessou = [];
		var naoAcessou = [];
		usoPorCursoData.forEach(
			function(a)
			{
				nomeCurso.push(a.NomeCurso);
				acessou.push(a.Atual);
				naoAcessou.push(a.Total - a.Atual);
			}
		);

		$('#usoPorCurso').highcharts({
				chart: {
					type: 'column'
				},
				title: {
					text: 'Quantidade de acessos por curso'
				},
				xAxis: {
					categories: nomeCurso,
					labels: {
						rotation: -45,
						style: {
							fontSize: '13px',
							fontFamily: 'Verdana, sans-serif'
						}
					}
				},
				yAxis: {
					min: 0,
					title: {
						text: 'Total de acessos'
					}
				},
				tooltip: {
					pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b> ({point.percentage:.0f}%)<br/>',
					shared: true
				},
				plotOptions: {
					column: {
						stacking: 'percent'
					}
				},
				series: [{
					name: 'Não acessou',
					data: naoAcessou 
				}, {
					name: 'Acessou',
					data: acessou
				}]
			});

	</script>
</body>

</html>
