<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#"><head><link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css" rel="stylesheet" type="text/css"><?php
	$lessfile = "/css/prisma-".$data["section"].".min.css";
	echo '<link href="'.$lessfile.'" rel="stylesheet" type="text/css" />';
?></head><meta charset="utf-8"><meta property="og:title" content="PrISMA"><meta property="og:type" content="website"><meta property="og:url" content="http://prisma.inf.puc-rio.br"><meta property="og:image" content=""><meta property="og:site_name" content="PrISMA"><meta property="fb:admins" content="100001586200753"><title>PrISMA: Programa de Instrução à Matrícula Acadêmica</title><body><?php
	$templatefile = "template/prisma-".$data["section"].".min.template";
	require($templatefile);
?><script>window.fbAsyncInit = function() {
 FB.init({
  status     : false,
  cookie     : true, // set sessions cookies to allow your server to access the session?
  xfbml      : true  // parse XFBML tags on this page?
 });
};

(function(d, debug){
 var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
 if (d.getElementById(id)) {return;}
 js = d.createElement('script'); js.id = id; js.async = true;
 js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
 ref.parentNode.insertBefore(js, ref);
}(document, /*debug*/ true));</script><script src="//www.youtube.com/iframe_api"></script><script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script><?php
	if(isset($data['DATA_VIEW'])):
?><script>var DATA_VIEW=<?php echo $data['DATA_VIEW'];?></script><?php
	endif;
?><script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.2/underscore-min.js"></script><script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.2/backbone-min.js"></script><script src="//cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/jquery.dataTables.min.js"></script><script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script><script type="text/javascript">less={env: 'development'};
</script><script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"></script><script src="//cdnjs.cloudflare.com/ajax/libs/less.js/1.3.1/less.min.js"></script><?php 
	 $jsfile = "/js/prisma-".$data["section"].".min.js";
	echo '<script type="text/javascript" src="'.$jsfile.'"></script>';
?></body></html>