<!DOCTYPE html>
<html>
	<head>
		<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css" rel="stylesheet" />
		<link rel="stylesheet" href="//code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" />
		<?php
			$lessfile = "css/prisma-".$data["section"].".min.css";
			echo '<link href="'.$lessfile.'" rel="stylesheet" type="text/css" />';
		?>

		<title>Prisma V2</title>
		<meta charset="utf-8" />


		</head>
	<body>
		<?php
			$templatefile = "template/prisma-".$data["section"].".min.template";
			require($templatefile);
		?>
	<!---	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	-->	
	<script src="//code.jquery.com/jquery-1.8.3.js"></script>
		
		<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.2/underscore-min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.2/backbone-min.js"></script>
		
		<script src="//cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/jquery.dataTables.min.js"></script>
		<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>


		<script type="text/javascript">	
			less={env: 'development'};
		</script>

		<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/1.3.1/less.min.js"></script>

		<?php 
			 $jsfile = "js/prisma-".$data["section"].".min.js";
			echo '<script type="text/javascript" src="'.$jsfile.'"></script>';
		?>
	</body>
</html>
